Updating ID 7
wit-week5/wit-week5.github.io pull request #9
Opened 2023-05-31 15:31 UTC by khinkyaingkyaingthein

Update ID and description

2023-06-01 12:19 UTC, smm-demo commented
ဒီ PR(Pull request) က conflict အရမ်းများနေတယ်ဗျ။
user အသုံးပြုတဲ့ text editor ကြောင့်သော်လည်းကောင်း လွဲသွားတာဖြစ်နိုင်ပါတယ်ဗျ။
Files changed မှာကြည့်မယ်ဆိုရင် တဖိုင်လုံးရဲ့ format တွေလွဲသွားတာကို တွေ့နိုင်ပါတယ်ဗျ။
Merge လို့အဆင်မပြေပါဘူး‌ခဗျ။

2023-06-01 12:24 UTC, smm-demo requested changes
မူလပုံစံနဲ့ format ပြန်ညှိဖို့ Request changes လုပ်လိုက်ပါတယ်ဗျ။

2023-06-01 18:34 UTC, khinkyaingkyaingthein commented
format ပြန်ညှိပြီး mark resolve ပြန်လုပ်ထားပါတယ်ရှင့်။

2023-06-07 10:52 UTC, smm-demo submitted a review, later dismissed

2023-06-07 11:16 UTC, smm-demo commented
format တွေက conflict ဖြစ်နေသေးတုန်းပါဗျ

2023-06-18 02:21 UTC, smm-demo commented
I will pull another PR instead of this one and close this

2023-06-18 02:21 UTC, closed without merging